import type { Config } from 'tailwindcss';

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        bg:      'var(--color-bg)',
        surface: 'var(--color-surface)',
        'surface-alt': 'var(--color-surface-alt)',
        border: {
          DEFAULT: 'var(--color-border)',
          strong:  'var(--color-border-strong)',
        },
        text: {
          primary:   'var(--color-text-primary)',
          secondary: 'var(--color-text-secondary)',
          tertiary:  'var(--color-text-tertiary)',
          inverse:   'var(--color-text-inverse)',
        },
        accent: {
          DEFAULT: 'var(--color-accent)',
          hover:   'var(--color-accent-hover)',
          subtle:  'var(--color-accent-subtle)',
        },
        success: { DEFAULT: 'var(--color-success)', subtle: 'var(--color-success-subtle)' },
        warning: { DEFAULT: 'var(--color-warning)', subtle: 'var(--color-warning-subtle)' },
        danger:  { DEFAULT: 'var(--color-danger)',  subtle: 'var(--color-danger-subtle)'  },
        info:    { DEFAULT: 'var(--color-info)',    subtle: 'var(--color-info-subtle)'    },
      },
      fontFamily: {
        sans:  ['var(--font-sans)'],
      },
      fontSize: {
        '2xs': ['11px', { lineHeight: '16px' }],
        xs:    ['13px', { lineHeight: '18px' }],
        sm:    ['14px', { lineHeight: '20px' }],
        base:  ['15px', { lineHeight: '23px' }],
        md:    ['16px', { lineHeight: '24px' }],
        lg:    ['18px', { lineHeight: '28px' }],
        xl:    ['22px', { lineHeight: '32px' }],
        '2xl': ['28px', { lineHeight: '36px' }],
        '3xl': ['36px', { lineHeight: '44px' }],
        '4xl': ['48px', { lineHeight: '56px' }],
        '5xl': ['64px', { lineHeight: '72px' }],
      },
      borderRadius: {
        xs:   'var(--radius-xs)',
        sm:   'var(--radius-sm)',
        md:   'var(--radius-md)',
        lg:   'var(--radius-lg)',
        xl:   'var(--radius-xl)',
        '2xl':'var(--radius-2xl)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        xs:     'var(--shadow-xs)',
        sm:     'var(--shadow-sm)',
        md:     'var(--shadow-md)',
        lg:     'var(--shadow-lg)',
        xl:     'var(--shadow-xl)',
        focus:  'var(--shadow-focus)',
        'focus-danger': 'var(--shadow-focus-danger)',
      },
      spacing: {
        0:   '0px',
        0.5: '2px',
        1:   '4px',
        1.5: '6px',
        2:   '8px',
        2.5: '10px',
        3:   '12px',
        3.5: '14px',
        4:   '16px',
        5:   '20px',
        6:   '24px',
        7:   '28px',
        8:   '32px',
        9:   '36px',
        10:  '40px',
        11:  '44px',
        12:  '48px',
        14:  '56px',
        16:  '64px',
        18:  '72px',
        20:  '80px',
        24:  '96px',
        28:  '112px',
        32:  '128px',
      },
      maxWidth: { content: 'var(--content-max-width)' },
      transitionTimingFunction: {
        'out':       'var(--ease-out)',
        'in-out':    'var(--ease-in-out)',
        'spring':    'var(--ease-spring)',
        'standard':  'var(--ease-standard)',
        'decelerate':'var(--ease-decelerate)',
      },
      transitionDuration: {
        instant: '80ms',
        fast:   '150ms',
        base:   '220ms',
        slow:   '350ms',
        slower: '500ms',
      },
      screens: {
        xs: '375px',
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        '2xl': '1536px',
      },
      letterSpacing: {
        tighter: '-0.04em',
        tight:   '-0.02em',
        normal:   '0',
        wide:     '0.05em',
        widest:   '0.12em',
      },
    },
  },
  plugins: [],
} satisfies Config;
