"""Initial schema sync

Revision ID: 0df81fdd63a6
Revises: 
Create Date: 2026-07-12 10:31:05.841545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision: str = '0df81fdd63a6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)

    with op.batch_alter_table('generations', schema=None) as batch_op:
        # Handle generations table indexes idempotently
        gen_indexes = [idx['name'] for idx in inspector.get_indexes('generations')]
        if 'idx_generations_user_id' in gen_indexes:
            batch_op.drop_index('idx_generations_user_id')
        if 'ix_generations_user_id' not in gen_indexes:
            batch_op.create_index(batch_op.f('ix_generations_user_id'), ['user_id'], unique=False)

    user_cols = [c['name'] for c in inspector.get_columns('users')]

    with op.batch_alter_table('users', schema=None) as batch_op:
        # Idempotently add missing columns for production databases
        if 'username' not in user_cols:
            batch_op.add_column(sa.Column('username', sa.String(), nullable=True))
            batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)
        if 'bio' not in user_cols:
            batch_op.add_column(sa.Column('bio', sa.String(), nullable=True))
        if 'theme_preference' not in user_cols:
            batch_op.add_column(sa.Column('theme_preference', sa.String(), nullable=False, server_default='system'))
        if 'email_notifications' not in user_cols:
            batch_op.add_column(sa.Column('email_notifications', sa.Integer(), nullable=False, server_default='1'))

        # Only run these if the constraints need updating (typically SQLite reflection artifacts)
        if 'idx_users_firebase_uid' in [idx['name'] for idx in inspector.get_indexes('users')]:
            batch_op.drop_index('idx_users_firebase_uid')
            batch_op.create_index(batch_op.f('ix_users_firebase_uid'), ['firebase_uid'], unique=True)

    pass

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_firebase_uid'))
        batch_op.create_index(batch_op.f('idx_users_firebase_uid'), ['firebase_uid'], unique=False)
        batch_op.alter_column('last_login_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('generations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generations_user_id'))
        batch_op.create_index(batch_op.f('idx_generations_user_id'), ['user_id'], unique=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
