"""baseline_schema

Revision ID: b2c0be7da680
Revises: 
Create Date: 2026-07-15 07:55:43.671376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2c0be7da680'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firebase_uid', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('active_text_provider', sa.String(), nullable=True),
    sa.Column('active_image_provider', sa.String(), nullable=True),
    sa.Column('theme_preference', sa.String(), nullable=False),
    sa.Column('email_notifications', sa.Integer(), nullable=False),
    sa.Column('profile_completed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('generations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('original_image_path', sa.String(), nullable=False),
    sa.Column('room_type_detected', sa.String(), nullable=True),
    sa.Column('room_confidence', sa.Float(), nullable=True),
    sa.Column('style', sa.String(), nullable=False),
    sa.Column('redesign_prompt', sa.String(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('analysis_json', sa.String(), nullable=True),
    sa.Column('parent_generation_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('provider_version', sa.String(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('processing_time_sec', sa.Float(), nullable=False),
    sa.Column('selected_variation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_generation_id'], ['generations.id'], ),
    sa.ForeignKeyConstraint(['selected_variation_id'], ['variations.id'], name='fk_generation_selected_variation_id', use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generations_user_id'), 'generations', ['user_id'], unique=False)
    op.create_index('ix_generations_user_status', 'generations', ['user_id', 'status', 'created_at'], unique=False)
    op.create_table('user_api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('encrypted_key', sa.String(), nullable=False),
    sa.Column('preferred_text_model', sa.String(), nullable=True),
    sa.Column('preferred_image_model', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_api_keys_user_id'), 'user_api_keys', ['user_id'], unique=False)
    op.create_table('variations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('generation_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('seed', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variations')
    op.drop_index(op.f('ix_user_api_keys_user_id'), table_name='user_api_keys')
    op.drop_table('user_api_keys')
    op.drop_index('ix_generations_user_status', table_name='generations')
    op.drop_index(op.f('ix_generations_user_id'), table_name='generations')
    op.drop_table('generations')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
