"""add_image_hash

Revision ID: fc95fd8ccd29
Revises: b2c0be7da680
Create Date: 2026-07-15 10:09:42.113731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc95fd8ccd29'
down_revision: Union[str, Sequence[str], None] = 'b2c0be7da680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generations', sa.Column('image_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_generations_image_hash'), 'generations', ['image_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generations_image_hash'), table_name='generations')
    op.drop_column('generations', 'image_hash')
    # ### end Alembic commands ###
